#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#2e7620"
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer      true
bspc config single_monocle true

# Set background color
hsetroot -solid "#1e1c31"
